import { Dog, Litter, News } from './types'

export const mockDogs: Dog[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    name: 'Donja vom Haus Englund',
    gender: 'female',
    birthdate: '2020-03-15',
    photo_url: '/dog1.jpg',
    working_dog_url: 'https://www.working-dog.com/dogs-ede/Donja-vom-Haus-Englund',
    sire_name: 'Rex von der Schiffslache',
    dam_name: 'Bella vom Haus Englund',
    hd_score: 'HD-A',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Rolig, selvsikker og meget kontaktsøgende. Viser ingen tegn på skyhed eller nervøsitet. Fremragende i nye miljøer.',
    training_results: 'BH/VT bestået med rosende bemærkninger. IPO1 med 285 point. Sporhund klasse 2.',
    achievements: 'V1 på Bundessieger 2022. Avlskåret med KKL1. Bedste tæve på klubskuet 2021.',
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    name: 'Rex vom Haus Englund',
    gender: 'male',
    birthdate: '2019-06-22',
    photo_url: '/dog2.jpg',
    working_dog_url: 'https://www.working-dog.com/dogs-ede/Rex-vom-Haus-Englund',
    sire_name: 'Aro vom Grafental',
    dam_name: 'Cira vom Haus Englund',
    hd_score: 'HD-A',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Kraftfuld, harmonisk og meget arbejdsvillig. Stærkt nervesystem og fremragende hårdhed. Klar og tydelig i sit væsen.',
    training_results: 'IPO3 med 292 point. FH2 bestået. BH/VT. Sporhund klasse 3.',
    achievements: 'VA på Bundessieger 2021. 2x V1 specialudstilling. Avlskåret KKL1. Landsmester spor 2023.',
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    name: 'Gina vom Haus Englund',
    gender: 'female',
    birthdate: '2022-01-10',
    photo_url: '/dog3.jpg',
    working_dog_url: 'https://www.working-dog.com/dogs-ede/Gina-vom-Haus-Englund',
    sire_name: 'Rex vom Haus Englund',
    dam_name: 'Donja vom Haus Englund',
    hd_score: 'HD-A',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Livlig og opmærksom med stærk drift. Meget social og tryg i alle situationer. Viser stor selvtillid.',
    training_results: 'BH/VT bestået. IPO1 med 280 point.',
    achievements: 'V1 ungdomsklasse på DM 2023. Mest lovende unghund 2023.',
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    name: 'Atos vom Haus Englund',
    gender: 'male',
    birthdate: '2021-09-05',
    sire_name: 'Rex vom Haus Englund',
    dam_name: 'Bella vom Haus Englund',
    hd_score: 'HD-B',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Venlig, åben og meget menneskeorienteret. God nervekontrol og fin balance mellem ro og aktivitet.',
    training_results: 'BH/VT bestået. IPO2 med 275 point. Sporhund klasse 1.',
    achievements: 'V2 åben klasse på klubskuet 2023. Godkendt avlshan.',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    name: 'Bellona vom Haus Mojü',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'DM: N/N',
    training_results: 'BH, StPr 1',
    achievements: 'Har den 15.05.23 født 2 hanner og 5 tæver efter Aldo Mersak.',
    extra_info: 'Bellona vom Haus Mojü har den 15.05.23 født 2 hanner og 5 tæver efter Aldo Mersak. Hvalpene kunne flytte d. 10.07.23.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/6434038/Bellona-vom-Haus-MoJ%C3%BC',
    photo_url: '/bellona.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0007-4000-8000-000000000007',
    name: 'Qutie von der Frisenklippe',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: null,
    training_results: 'Tysk index 75',
    achievements: 'Har d. 1. februar født 4 hanner og 3 tæver.',
    extra_info: 'Qutie von der Frisenklippe bliver start december 2025 parret med Spike vom Adlerschrei. Begge har store kvaliteter. Hvalpene vil egnet sig perfekt til sport og tjenestehunde. Begge hunde har sundhed langt over middel, og begge er avlskåret. Vi planlægger nyt kuld i løbet af 2025. Reservationer er påbegyndt.\n\nFar til hvalpene er Alonso vom Verbotenen Wald.\n\nQutie er ud af en virkelig god brugshundelinie.\n\nVi har ledt en del efter endnu en tæve til vores avlsarbejde.\n\nDa vi fik muligheden for at købe Qutie måtte vi selvfølgelig gøre det.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/7210096/Qutie-von-der-Friesenklippe',
    photo_url: '/qutie.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockLitters: Litter[] = [
  {
    id: 'b1b2c3d4-0001-4000-8000-000000000001',
    sire_name: 'Rex vom Haus Englund',
    dam_name: 'Donja vom Haus Englund',
    birth_date: '2025-04-20',
    males_count: 4,
    females_count: 3,
    available: true,
    description: 'Fantastisk kuld med 7 sunde og livlige hvalpe. Begge forældre er HD-A og mentalt beskrevne med fremragende resultater. Hvalpene er opdrættet i hjemmet med tidlig stimulering og socialisering. 2 hanner og 1 tæve er stadig ledige.',
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'b1b2c3d4-0002-4000-8000-000000000002',
    sire_name: 'Atos vom Haus Englund',
    dam_name: 'Gina vom Haus Englund',
    birth_date: null,
    males_count: 0,
    females_count: 0,
    available: false,
    description: 'Vi planlægger et nyt kuld til efteråret 2025. Gina vil blive parret med Atos for en spændende kombination af arbejdsevne og fantastisk mentalitet. Kontakt os for at komme på ventelisten.',
    created_at: '2025-05-01T00:00:00Z',
  },
]

export const mockNews: News[] = [
  {
    id: 'c1b2c3d4-0001-4000-8000-000000000001',
    title: 'Rex opnår VA på Bundessieger!',
    content: 'Vi er utroligt stolte over at vores Rex vom Haus Englund har opnået den fornemme VA-placering (Vorzüglich Auslese) på årets Bundessieger i Nürnberg. Det er en enorm anerkendelse af hans kvalitet som avlshan og en milepæl for vores kennel. Rex viste sig fra sin bedste side med fantastisk bevægelse og temperament. Tak til alle der hepper på os!',
    photo_path: null,
    published_at: '2025-05-15T00:00:00Z',
    created_at: '2025-05-15T00:00:00Z',
  },
  {
    id: 'c1b2c3d4-0002-4000-8000-000000000002',
    title: 'Nye hvalpe er født!',
    content: 'Den 20. april blev vi velsignet med et smukt kuld på 7 hvalpe fra Rex og Donja. 4 hanner og 3 tæver, alle sunde og stærke. Moderen har det fantastisk og hvalpene vokser som ukrudt. Vi begynder med besøgstider fra uge 5. Kontakt os hvis du er interesseret.',
    photo_path: null,
    published_at: '2025-04-20T00:00:00Z',
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'c1b2c3d4-0003-4000-8000-000000000003',
    title: 'Gina bestod IPO1 med bravur',
    content: 'Vores unge Gina vom Haus Englund bestod i dag sin IPO1-prøve med imponerende 280 point. Hun viste sig særligt stærk i spordisciplinen med 96 point. Vi er meget tilfredse med hendes udvikling og ser frem til næste trin i hendes uddannelse.',
    photo_path: null,
    published_at: '2025-03-10T00:00:00Z',
    created_at: '2025-03-10T00:00:00Z',
  },
]
