import { Dog, Litter, News } from './types'

export const mockDogs: Dog[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    name: 'Donja vom Haus Englund',
    gender: 'female',
    birthdate: '2020-03-15',
    photo_url: '/dog1.jpg',
    working_dog_url: 'https://www.working-dog.com/dogs-ede/Donja-vom-Haus-Englund',
    sire_name: 'Rex von der Schiffslache',
    dam_name: 'Bella vom Haus Englund',
    hd_score: 'HD-A',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Rolig, selvsikker og meget kontaktsøgende. Viser ingen tegn på skyhed eller nervøsitet. Fremragende i nye miljøer.',
    training_results: 'BH/VT bestået med rosende bemærkninger. IPO1 med 285 point. Sporhund klasse 2.',
    achievements: 'V1 på Bundessieger 2022. Avlskåret med KKL1. Bedste tæve på klubskuet 2021.',
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    name: 'Rex vom Haus Englund',
    gender: 'male',
    birthdate: '2019-06-22',
    photo_url: '/dog2.jpg',
    working_dog_url: 'https://www.working-dog.com/dogs-ede/Rex-vom-Haus-Englund',
    sire_name: 'Aro vom Grafental',
    dam_name: 'Cira vom Haus Englund',
    hd_score: 'HD-A',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Kraftfuld, harmonisk og meget arbejdsvillig. Stærkt nervesystem og fremragende hårdhed. Klar og tydelig i sit væsen.',
    training_results: 'IPO3 med 292 point. FH2 bestået. BH/VT. Sporhund klasse 3.',
    achievements: 'VA på Bundessieger 2021. 2x V1 specialudstilling. Avlskåret KKL1. Landsmester spor 2023.',
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    name: 'Gina vom Haus Englund',
    gender: 'female',
    birthdate: '2022-01-10',
    photo_url: '/dog3.jpg',
    working_dog_url: 'https://www.working-dog.com/dogs-ede/Gina-vom-Haus-Englund',
    sire_name: 'Rex vom Haus Englund',
    dam_name: 'Donja vom Haus Englund',
    hd_score: 'HD-A',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Livlig og opmærksom med stærk drift. Meget social og tryg i alle situationer. Viser stor selvtillid.',
    training_results: 'BH/VT bestået. IPO1 med 280 point.',
    achievements: 'V1 ungdomsklasse på DM 2023. Mest lovende unghund 2023.',
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    name: 'Atos vom Haus Englund',
    gender: 'male',
    birthdate: '2021-09-05',
    sire_name: 'Rex vom Haus Englund',
    dam_name: 'Bella vom Haus Englund',
    hd_score: 'HD-B',
    ad_score: 'AD 0/0',
    ocd_status: 'Fri',
    mental_description: 'Venlig, åben og meget menneskeorienteret. God nervekontrol og fin balance mellem ro og aktivitet.',
    training_results: 'BH/VT bestået. IPO2 med 275 point. Sporhund klasse 1.',
    achievements: 'V2 åben klasse på klubskuet 2023. Godkendt avlshan.',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    name: 'Bellona vom Haus Mojü',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'DM: N/N',
    training_results: 'BH, StPr 1',
    achievements: 'Har den 15.05.23 født 2 hanner og 5 tæver efter Aldo Mersak.',
    extra_info: 'Bellona vom Haus Mojü har den 15.05.23 født 2 hanner og 5 tæver efter Aldo Mersak. Hvalpene kunne flytte d. 10.07.23.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/6434038/Bellona-vom-Haus-MoJ%C3%BC',
    photo_url: '/bellona.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0008-4000-8000-000000000008',
    name: 'Cartagena Electra',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'LÜW: 0',
    training_results: 'BH + EDD Search Dog',
    achievements: null,
    working_dog_url: 'https://www.working-dog.com/dogs-details/6975748/Cartagena-Electra',
    photo_url: '/cartagena.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0009-4000-8000-000000000009',
    name: "Team Englund's Fanni",
    gender: 'female',
    birthdate: null,
    sire_name: "Jen-Ager's Odin",
    dam_name: "Team Englund's Berta",
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Et festfyrværkeri af en hund er det man først tænker, når man har set Fanni arbejde. Hun har en ekstrem drift og arbejdsglæde. Hun sætter super fine greb. Hun er en nem, omgængelig og social hund. Hun er meget sikker i miljø. Sundheden er helt i top – yderligere er hun en ganske køn hund.',
    training_results: 'Færdelsprøve, UHP, IPO1, Skue: G. Avlskåret 2019–2020. Index 110.',
    achievements: 'Fanni har d. 13.09.19 fået hvalpe efter Nederholms Quik. MDR 1: N/N – DM: N/N.',
    extra_info: 'DK04733/2015\n\nBegge forældre, Team Englunds Berta og Jen-Agers Odin er begge rigtig gode "næsehunde" – Odin er bl.a. mønstret i gr. 1 i Dansk Politi. Berta er ud af søskeneflok på 9, hvoraf 4 hanner lavede yderst overbevisende mentaltest i Dansk Politi.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/4954619/Team-Englunds-Fanni',
    photo_url: '/fanni.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0010-4000-8000-000000000010',
    name: "Team Englund's Eia",
    gender: 'female',
    birthdate: null,
    sire_name: 'Coudy Z Udoli Upy',
    dam_name: 'Toftegården Nessi',
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Eia er en super spændende tæve. Hun er ret driftig og hele tiden arbejdsivrig. Hun er meget sporglad. Hun bider godt og er en god halsgiver. Hun er miljøstærk og generelt en meget robust og "cool" tæve, der tåler en del belastning. Hun er omgængelig og indgår i det daglige som familiehund.',
    training_results: 'IPO 1, PH kåring, Færdelsprøve, UHP, Skue: G. Livstidskåret 2019. Index 106.',
    achievements: 'Fra Eias første kuld har alle afkom lavet brugsprøver og er i sporten.',
    extra_info: 'DK16739/2014\n\nD. 06.07.20: Team Englunds Eia har født 3 hanner og 3 tæver efter Audi Catario Mikels. Dette er en kuldgentagelse for Q kuldet. Alle hvalpe er solgt på reservation.\n\nD. 13.11.19: Team Englunds Eia har født 2 hanner og 4 tæver efter Audi Catario Mikels.\n\nAudi har en rigtig god ro i hovedet, også som familiehund og hviler rigtig godt i sig selv.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2840047/Team-Englunds-Eia',
    photo_url: '/eia.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0011-4000-8000-000000000011',
    name: "Lærkbo's Jackie",
    gender: 'female',
    birthdate: '2013-11-26',
    sire_name: null,
    dam_name: null,
    hd_score: null,
    ad_score: null,
    ocd_status: null,
    mental_description: null,
    training_results: null,
    achievements: 'Mor til vores "L" og "O" kuld.',
    extra_info: 'DK 19871/2013\nStockhaar, 58 cm / 26 kg\nFødt: 26.11.2013 – Død: 01.12.2022',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2840054/Laerkbos-Jackie',
    photo_url: '/jackie.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0012-4000-8000-000000000012',
    name: 'Bayogi Yenka',
    gender: 'female',
    birthdate: null,
    sire_name: 'Dago von Weltwitz',
    dam_name: 'Bayogi Xanti',
    hd_score: 'HD-A',
    ad_score: 'AD 1',
    ocd_status: null,
    mental_description: 'Yenka er en energisk og driftig tæve med et super temperament, og et helt igennem sundt nervesystem. Hun er meget vedholdende i hendes søg, og sætter gode greb. Hun er en naturlig halsgiver. I lydighedsøvelserne arbejder hun med stor glæde og energi. Hun er meget lærenem og husker momenter og øvelser godt. Når hun ikke arbejder/træner er hun god til at finde ro. Hun indgår i familien som en afbalanceret hund.',
    training_results: 'Dansk Politihundeforening – Vinderklassen, Færdelsprøve, Skue: SG. Index 99. Kåret i Dansk Politihundeforening med 107,8 point.',
    achievements: 'I 2015 kvalificerede hun sig til DM i kriminalklassen. Yenka er flot og velproportioneret og har på 2 skuer opnået SG.',
    extra_info: 'DK05974/2011\n\nYenka har d. 01.08.18 født 7 hanner og 1 tæve efter Irck de la Hutte du Berger, tysk mester IPO 3 2017 og VM deltager 2017.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/2538804/Bayogi-Yenka',
    photo_url: '/yenka.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0013-4000-8000-000000000013',
    name: "Team Englund's Berta",
    gender: 'female',
    birthdate: '2011-08-21',
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-B',
    ad_score: 'AD 1',
    ocd_status: null,
    mental_description: 'Berta er ud af søskeneflok på 9, hvoraf 4 hanner lavede yderst overbevisende mentaltest i Dansk Politi.',
    training_results: 'IPO 1, Skue: G, Kkl 1. Index 108.',
    achievements: 'Mor til Team Englunds Fanni.',
    extra_info: 'DK 15093\nStockhaar, 57 cm / 28 kg\nFødt: 21.08.2011',
    working_dog_url: 'https://www.working-dog.com/dogs-details/1042249/Team-Englund%C2%B4s-Berta',
    photo_url: '/berta.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0014-4000-8000-000000000014',
    name: 'Toftegården Nessi',
    gender: 'female',
    birthdate: null,
    sire_name: 'Chef von der Fasanerie',
    dam_name: 'Bayogi Kira',
    hd_score: 'HD-B',
    ad_score: 'AD 1',
    ocd_status: null,
    mental_description: 'Nessi er en dejlig og meget hurtig tæve med appel i alt, hvad hun laver. Hendes engagement i opgaverne er stor. Grebene er gode og dybe. I søgeopgaverne er hun vedholdende og markerer med stor sikkerhed og hastighed. Hendes energi og glæde, lege- og arbejdslæde er nærmest uudtømmelig. Udenfor træningsbanen er hun en velfungerende hund. På miljøsiden er hun sikker og bevæger sig frit og hurtigt.',
    training_results: 'FP, UHP, PH-kåring 105,9 points. Index 100. Skue: G.',
    achievements: 'Mor til vores A, B, C, D, E og G kuld. Mor til 2 DM guld vindere i Dansk Politihundeforening, og et stort antal tjenestehunde i politiet.',
    extra_info: 'DK01849/2008\n\nNessi er mor til 33 hvalpe. 9 stk. er fotograferet. 6 har A – 3 har B og 1 har D hofter. Albuer 0 og 1.\n\nFra Nessis kuld er 3 tjenestehunde i politiet. De har lavet rigtig gode mentaltests og fungerer særdeles godt bl.a. som gr. I hunde og nedgravningshunde.\n\nNessi blev også stillet i den internationale udstilling FCI "Paasshow", Holland med prædikatet: Excellent og dermed avlsgodkendt.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/994301/Toftegarden-Nessi',
    photo_url: '/nessi.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0015-4000-8000-000000000015',
    name: "Team Englund's Unik",
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-B',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'Unik er en hund med et virkelig sundt væsen. Han har masser af power – sætter gode greb og gør/bevogter med den rigtige attitude. Han har en super stamtavle – perfekt størrelse.',
    training_results: 'Policedog, BH, Skue: SG, WB, PH Kåring, Godkendt tjenestehund.',
    extra_info: 'DM: N/N – MDR: N/N – Pituitary Dwarfism: N/N\nCoat length: L/l',
    achievements: null,
    working_dog_url: 'https://www.working-dog.com/dogs-details/7638256/Team-Englunds-Unik',
    photo_url: '/unik.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0016-4000-8000-000000000016',
    name: 'Alonso vom Verbotenen Wald',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-Normal',
    ad_score: 'ED-Normal',
    ocd_status: 'Fri',
    mental_description: 'LÜW: 0. DNA geprüft SV. Alonso besitzt eine Zuchtzulassung für Deutschland.',
    training_results: 'IGP 1: A:98 B:93 C:97 = 288 point. IGP 2: A:99 B:88 C:94 = 281 point.',
    achievements: 'Avlsgodkendt i Tyskland (Zuchtzulassung).',
    extra_info: 'Far til hvalpene fra Qutie von der Frisenklippe.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/7330100/Alonso-vom-verbotenen-Wald',
    photo_url: '/alonso.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0017-4000-8000-000000000017',
    name: 'Aldo Mersak',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'Aldo er en hund med et virkelig sundt væsen. Han har masser af power – sætter gode greb og gør/bevogter med den rigtige attitude. Han har en super stamtavle – perfekt størrelse og fint pigment.',
    training_results: 'LTV1: Fri.',
    achievements: 'Far til U-kuldet (Bellona vom Haus Mojü & Aldo Mersak).',
    working_dog_url: null,
    photo_url: '/aldo.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0018-4000-8000-000000000018',
    name: 'CZ Nirreterrit',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Lüw: 0.',
    training_results: 'IGP 2.',
    achievements: 'CZ har d. 22.06.2023 parret Qutie von der Frisenklippe. D. 24.08.2023 er der kommet 3 hanner og 2 tæver.',
    extra_info: 'CMKU DS/118765/19\n\nVi forventer særdeles brugsstærke hvalpe med top sundhed.',
    working_dog_url: null,
    photo_url: '/nirreterrit.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0019-4000-8000-000000000019',
    name: 'Coast Strikers Alvin',
    gender: 'male',
    birthdate: null,
    sire_name: 'Freggel vom tapferen Kriger',
    dam_name: 'Nena vom Osterburg Quell',
    hd_score: 'HD-Normal',
    ad_score: 'AD-Normal',
    ocd_status: null,
    mental_description: 'En glad og arbejdsivrig hund, der sætter gode faste greb. Ligeledes i lydighed arbejder han ivrig og aktivt. Alvin har et sikkert væsen og er på alle måder en omgængelig og helt reel hund. Alvin har en perfekt størrelse på 63,5 cm. Yderligere er han en smuk hund, der har udstillingsresultatet: Fortrinlig.',
    training_results: 'IGP 3: A:99 B:96 C:96 = 291 point. DM: N/N.',
    achievements: 'Coast Strikers Alvin har d. 13.01.2020 parret Team Englunds Gabby. Udstilling: Fortrinlig.',
    extra_info: 'VDH/SZ 23332',
    working_dog_url: null,
    photo_url: '/alvin.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0020-4000-8000-000000000020',
    name: 'Audi Catario Mikels',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Audi er en robust og maskulin han – der ved hvad han vil. Han er insisterende i sit arbejde. Han sætter gode greb og gør godt. Han er på alle måder en fryd for øjet. Ud over arbejdet på banen, bevæger han sig rigtig godt på sine ben. Han har flotte mørke farver og et maskulint hoved.',
    training_results: 'IGP 1: A:98 B:94 C:94. Vinder af Danmarks Bedste Begynder B med 98 point.',
    achievements: 'Audi Catario Mikels har d. 13.09.19 parret Team Englunds Eia.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2619064/Audi-Catario-Mikels',
    photo_url: '/audi.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0021-4000-8000-000000000021',
    name: "Nederholm's Quik",
    gender: 'male',
    birthdate: null,
    sire_name: "Degn's Lennon",
    dam_name: "Nederholm's Holly",
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Quik er en velfungerende politi tjenestehund på 7 år. Han er mønstret i gr. 1. Han har stor koncentrationsevne i søgeopgaverne, bider og gør rigtig godt. Han er absolut sund i hovedet på alle måder.',
    training_results: 'Aktiv politihund GR. 1. Mønstret i gr. 1. Avlskåret. Index 119. DM: N/N.',
    achievements: 'DM vinder af vinderklassen 2018, Dansk Politihundeforening. Nederholms Quik har parret Team Englunds Fanni.',
    extra_info: 'Super sundhedsstatistik på 10 kuld i DK: 13 hunde røntgenfotograferet – 12 stk. med HD:A + AD:0, 1 stk. med HD:B + AD:0.',
    working_dog_url: null,
    photo_url: '/quik.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0007-4000-8000-000000000007',
    name: 'Qutie von der Frisenklippe',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: null,
    training_results: 'Tysk index 75',
    achievements: 'Har d. 1. februar født 4 hanner og 3 tæver.',
    extra_info: 'Qutie von der Frisenklippe bliver start december 2025 parret med Spike vom Adlerschrei. Begge har store kvaliteter. Hvalpene vil egnet sig perfekt til sport og tjenestehunde. Begge hunde har sundhed langt over middel, og begge er avlskåret. Vi planlægger nyt kuld i løbet af 2025. Reservationer er påbegyndt.\n\nFar til hvalpene er Alonso vom Verbotenen Wald.\n\nQutie er ud af en virkelig god brugshundelinie.\n\nVi har ledt en del efter endnu en tæve til vores avlsarbejde.\n\nDa vi fik muligheden for at købe Qutie måtte vi selvfølgelig gøre det.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/7210096/Qutie-von-der-Friesenklippe',
    photo_url: '/qutie.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockLitters: Litter[] = [
  {
    id: 'b1b2c3d4-0001-4000-8000-000000000001',
    sire_name: 'Rex vom Haus Englund',
    dam_name: 'Donja vom Haus Englund',
    birth_date: '2025-04-20',
    males_count: 4,
    females_count: 3,
    available: true,
    description: 'Fantastisk kuld med 7 sunde og livlige hvalpe. Begge forældre er HD-A og mentalt beskrevne med fremragende resultater. Hvalpene er opdrættet i hjemmet med tidlig stimulering og socialisering. 2 hanner og 1 tæve er stadig ledige.',
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'b1b2c3d4-0002-4000-8000-000000000002',
    sire_name: 'Atos vom Haus Englund',
    dam_name: 'Gina vom Haus Englund',
    birth_date: null,
    males_count: 0,
    females_count: 0,
    available: false,
    description: 'Vi planlægger et nyt kuld til efteråret 2025. Gina vil blive parret med Atos for en spændende kombination af arbejdsevne og fantastisk mentalitet. Kontakt os for at komme på ventelisten.',
    created_at: '2025-05-01T00:00:00Z',
  },
]

export const mockNews: News[] = [
  {
    id: 'c1b2c3d4-0001-4000-8000-000000000001',
    title: 'Rex opnår VA på Bundessieger!',
    content: 'Vi er utroligt stolte over at vores Rex vom Haus Englund har opnået den fornemme VA-placering (Vorzüglich Auslese) på årets Bundessieger i Nürnberg. Det er en enorm anerkendelse af hans kvalitet som avlshan og en milepæl for vores kennel. Rex viste sig fra sin bedste side med fantastisk bevægelse og temperament. Tak til alle der hepper på os!',
    photo_path: null,
    published_at: '2025-05-15T00:00:00Z',
    created_at: '2025-05-15T00:00:00Z',
  },
  {
    id: 'c1b2c3d4-0002-4000-8000-000000000002',
    title: 'Nye hvalpe er født!',
    content: 'Den 20. april blev vi velsignet med et smukt kuld på 7 hvalpe fra Rex og Donja. 4 hanner og 3 tæver, alle sunde og stærke. Moderen har det fantastisk og hvalpene vokser som ukrudt. Vi begynder med besøgstider fra uge 5. Kontakt os hvis du er interesseret.',
    photo_path: null,
    published_at: '2025-04-20T00:00:00Z',
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'c1b2c3d4-0003-4000-8000-000000000003',
    title: 'Gina bestod IPO1 med bravur',
    content: 'Vores unge Gina vom Haus Englund bestod i dag sin IPO1-prøve med imponerende 280 point. Hun viste sig særligt stærk i spordisciplinen med 96 point. Vi er meget tilfredse med hendes udvikling og ser frem til næste trin i hendes uddannelse.',
    photo_path: null,
    published_at: '2025-03-10T00:00:00Z',
    created_at: '2025-03-10T00:00:00Z',
  },
]
