import { Dog, Litter, News } from './types'

export const mockDogs: Dog[] = [
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    name: 'Bellona vom Haus Mojü',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'DM: N/N',
    training_results: 'BH, StPr 1',
    achievements: 'Har den 15.05.23 født 2 hanner og 5 tæver efter Aldo Mersak.',
    extra_info: 'Bellona vom Haus Mojü har den 15.05.23 født 2 hanner og 5 tæver efter Aldo Mersak. Hvalpene kunne flytte d. 10.07.23.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/6434038/Bellona-vom-Haus-MoJ%C3%BC',
    photo_url: '/bellona.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0008-4000-8000-000000000008',
    name: 'Cartagena Electra',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'LÜW: 0',
    training_results: 'BH + EDD Search Dog',
    achievements: null,
    working_dog_url: 'https://www.working-dog.com/dogs-details/6975748/Cartagena-Electra',
    photo_url: '/cartagena.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0009-4000-8000-000000000009',
    name: "Team Englund's Fanni",
    gender: 'female',
    birthdate: null,
    sire_name: "Jen-Ager's Odin",
    dam_name: "Team Englund's Berta",
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Et festfyrværkeri af en hund er det man først tænker, når man har set Fanni arbejde. Hun har en ekstrem drift og arbejdsglæde. Hun sætter super fine greb. Hun er en nem, omgængelig og social hund. Hun er meget sikker i miljø. Sundheden er helt i top – yderligere er hun en ganske køn hund.',
    training_results: 'Færdelsprøve, UHP, IPO1, Skue: G. Avlskåret 2019–2020. Index 110.',
    achievements: 'Fanni har d. 13.09.19 fået hvalpe efter Nederholms Quik. MDR 1: N/N – DM: N/N.',
    extra_info: 'DK04733/2015\n\nBegge forældre, Team Englunds Berta og Jen-Agers Odin er begge rigtig gode "næsehunde" – Odin er bl.a. mønstret i gr. 1 i Dansk Politi. Berta er ud af søskeneflok på 9, hvoraf 4 hanner lavede yderst overbevisende mentaltest i Dansk Politi.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/4954619/Team-Englunds-Fanni',
    photo_url: '/fanni.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0010-4000-8000-000000000010',
    name: "Team Englund's Eia",
    gender: 'female',
    birthdate: null,
    sire_name: 'Coudy Z Udoli Upy',
    dam_name: 'Toftegården Nessi',
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Eia er en super spændende tæve. Hun er ret driftig og hele tiden arbejdsivrig. Hun er meget sporglad. Hun bider godt og er en god halsgiver. Hun er miljøstærk og generelt en meget robust og "cool" tæve, der tåler en del belastning. Hun er omgængelig og indgår i det daglige som familiehund.',
    training_results: 'IPO 1, PH kåring, Færdelsprøve, UHP, Skue: G. Livstidskåret 2019. Index 106.',
    achievements: 'Fra Eias første kuld har alle afkom lavet brugsprøver og er i sporten.',
    extra_info: 'DK16739/2014\n\nD. 06.07.20: Team Englunds Eia har født 3 hanner og 3 tæver efter Audi Catario Mikels. Dette er en kuldgentagelse for Q kuldet. Alle hvalpe er solgt på reservation.\n\nD. 13.11.19: Team Englunds Eia har født 2 hanner og 4 tæver efter Audi Catario Mikels.\n\nAudi har en rigtig god ro i hovedet, også som familiehund og hviler rigtig godt i sig selv.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2840047/Team-Englunds-Eia',
    photo_url: '/eia.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0011-4000-8000-000000000011',
    name: "Lærkbo's Jackie",
    gender: 'female',
    birthdate: '2013-11-26',
    sire_name: null,
    dam_name: null,
    hd_score: null,
    ad_score: null,
    ocd_status: null,
    mental_description: null,
    training_results: null,
    achievements: 'Mor til vores "L" og "O" kuld.',
    extra_info: 'DK 19871/2013\nStockhaar, 58 cm / 26 kg\nFødt: 26.11.2013 – Død: 01.12.2022',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2840054/Laerkbos-Jackie',
    photo_url: '/jackie.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0012-4000-8000-000000000012',
    name: 'Bayogi Yenka',
    gender: 'female',
    birthdate: null,
    sire_name: 'Dago von Weltwitz',
    dam_name: 'Bayogi Xanti',
    hd_score: 'HD-A',
    ad_score: 'AD 1',
    ocd_status: null,
    mental_description: 'Yenka er en energisk og driftig tæve med et super temperament, og et helt igennem sundt nervesystem. Hun er meget vedholdende i hendes søg, og sætter gode greb. Hun er en naturlig halsgiver. I lydighedsøvelserne arbejder hun med stor glæde og energi. Hun er meget lærenem og husker momenter og øvelser godt. Når hun ikke arbejder/træner er hun god til at finde ro. Hun indgår i familien som en afbalanceret hund.',
    training_results: 'Dansk Politihundeforening – Vinderklassen, Færdelsprøve, Skue: SG. Index 99. Kåret i Dansk Politihundeforening med 107,8 point.',
    achievements: 'I 2015 kvalificerede hun sig til DM i kriminalklassen. Yenka er flot og velproportioneret og har på 2 skuer opnået SG.',
    extra_info: 'DK05974/2011\n\nYenka har d. 01.08.18 født 7 hanner og 1 tæve efter Irck de la Hutte du Berger, tysk mester IPO 3 2017 og VM deltager 2017.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/2538804/Bayogi-Yenka',
    photo_url: '/yenka.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0013-4000-8000-000000000013',
    name: "Team Englund's Berta",
    gender: 'female',
    birthdate: '2011-08-21',
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-B',
    ad_score: 'AD 1',
    ocd_status: null,
    mental_description: 'Berta er ud af søskeneflok på 9, hvoraf 4 hanner lavede yderst overbevisende mentaltest i Dansk Politi.',
    training_results: 'IPO 1, Skue: G, Kkl 1. Index 108.',
    achievements: 'Mor til Team Englunds Fanni.',
    extra_info: 'DK 15093\nStockhaar, 57 cm / 28 kg\nFødt: 21.08.2011',
    working_dog_url: 'https://www.working-dog.com/dogs-details/1042249/Team-Englund%C2%B4s-Berta',
    photo_url: '/berta.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0014-4000-8000-000000000014',
    name: 'Toftegården Nessi',
    gender: 'female',
    birthdate: null,
    sire_name: 'Chef von der Fasanerie',
    dam_name: 'Bayogi Kira',
    hd_score: 'HD-B',
    ad_score: 'AD 1',
    ocd_status: null,
    mental_description: 'Nessi er en dejlig og meget hurtig tæve med appel i alt, hvad hun laver. Hendes engagement i opgaverne er stor. Grebene er gode og dybe. I søgeopgaverne er hun vedholdende og markerer med stor sikkerhed og hastighed. Hendes energi og glæde, lege- og arbejdslæde er nærmest uudtømmelig. Udenfor træningsbanen er hun en velfungerende hund. På miljøsiden er hun sikker og bevæger sig frit og hurtigt.',
    training_results: 'FP, UHP, PH-kåring 105,9 points. Index 100. Skue: G.',
    achievements: 'Mor til vores A, B, C, D, E og G kuld. Mor til 2 DM guld vindere i Dansk Politihundeforening, og et stort antal tjenestehunde i politiet.',
    extra_info: 'DK01849/2008\n\nNessi er mor til 33 hvalpe. 9 stk. er fotograferet. 6 har A – 3 har B og 1 har D hofter. Albuer 0 og 1.\n\nFra Nessis kuld er 3 tjenestehunde i politiet. De har lavet rigtig gode mentaltests og fungerer særdeles godt bl.a. som gr. I hunde og nedgravningshunde.\n\nNessi blev også stillet i den internationale udstilling FCI "Paasshow", Holland med prædikatet: Excellent og dermed avlsgodkendt.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/994301/Toftegarden-Nessi',
    photo_url: '/nessi.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0015-4000-8000-000000000015',
    name: "Team Englund's Unik",
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-B',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'Unik er en hund med et virkelig sundt væsen. Han har masser af power – sætter gode greb og gør/bevogter med den rigtige attitude. Han har en super stamtavle – perfekt størrelse.',
    training_results: 'Policedog, BH, Skue: SG, WB, PH Kåring, Godkendt tjenestehund.',
    extra_info: 'DM: N/N – MDR: N/N – Pituitary Dwarfism: N/N\nCoat length: L/l',
    achievements: null,
    working_dog_url: 'https://www.working-dog.com/dogs-details/7638256/Team-Englunds-Unik',
    photo_url: '/unik.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0016-4000-8000-000000000016',
    name: 'Alonso vom Verbotenen Wald',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-Normal',
    ad_score: 'ED-Normal',
    ocd_status: 'Fri',
    mental_description: 'LÜW: 0. DNA geprüft SV. Alonso besitzt eine Zuchtzulassung für Deutschland.',
    training_results: 'IGP 1: A:98 B:93 C:97 = 288 point. IGP 2: A:99 B:88 C:94 = 281 point.',
    achievements: 'Avlsgodkendt i Tyskland (Zuchtzulassung).',
    extra_info: 'Far til hvalpene fra Qutie von der Frisenklippe.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/7330100/Alonso-vom-verbotenen-Wald',
    photo_url: '/alonso.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0017-4000-8000-000000000017',
    name: 'Aldo Mersak',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Fri',
    mental_description: 'Aldo er en hund med et virkelig sundt væsen. Han har masser af power – sætter gode greb og gør/bevogter med den rigtige attitude. Han har en super stamtavle – perfekt størrelse og fint pigment.',
    training_results: 'LTV1: Fri.',
    achievements: 'Far til U-kuldet (Bellona vom Haus Mojü & Aldo Mersak).',
    working_dog_url: null,
    photo_url: '/aldo.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0018-4000-8000-000000000018',
    name: 'CZ Nirreterrit',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Lüw: 0.',
    training_results: 'IGP 2.',
    achievements: 'CZ har d. 22.06.2023 parret Qutie von der Frisenklippe. D. 24.08.2023 er der kommet 3 hanner og 2 tæver.',
    extra_info: 'CMKU DS/118765/19\n\nVi forventer særdeles brugsstærke hvalpe med top sundhed.',
    working_dog_url: null,
    photo_url: '/nirreterrit.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0019-4000-8000-000000000019',
    name: 'Coast Strikers Alvin',
    gender: 'male',
    birthdate: null,
    sire_name: 'Freggel vom tapferen Kriger',
    dam_name: 'Nena vom Osterburg Quell',
    hd_score: 'HD-Normal',
    ad_score: 'AD-Normal',
    ocd_status: null,
    mental_description: 'En glad og arbejdsivrig hund, der sætter gode faste greb. Ligeledes i lydighed arbejder han ivrig og aktivt. Alvin har et sikkert væsen og er på alle måder en omgængelig og helt reel hund. Alvin har en perfekt størrelse på 63,5 cm. Yderligere er han en smuk hund, der har udstillingsresultatet: Fortrinlig.',
    training_results: 'IGP 3: A:99 B:96 C:96 = 291 point. DM: N/N.',
    achievements: 'Coast Strikers Alvin har d. 13.01.2020 parret Team Englunds Gabby. Udstilling: Fortrinlig.',
    extra_info: 'VDH/SZ 23332',
    working_dog_url: null,
    photo_url: '/alvin.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0020-4000-8000-000000000020',
    name: 'Audi Catario Mikels',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Audi er en robust og maskulin han – der ved hvad han vil. Han er insisterende i sit arbejde. Han sætter gode greb og gør godt. Han er på alle måder en fryd for øjet. Ud over arbejdet på banen, bevæger han sig rigtig godt på sine ben. Han har flotte mørke farver og et maskulint hoved.',
    training_results: 'IGP 1: A:98 B:94 C:94. Vinder af Danmarks Bedste Begynder B med 98 point.',
    achievements: 'Audi Catario Mikels har d. 13.09.19 parret Team Englunds Eia.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2619064/Audi-Catario-Mikels',
    photo_url: '/audi.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0021-4000-8000-000000000021',
    name: "Nederholm's Quik",
    gender: 'male',
    birthdate: null,
    sire_name: "Degn's Lennon",
    dam_name: "Nederholm's Holly",
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Quik er en velfungerende politi tjenestehund på 7 år. Han er mønstret i gr. 1. Han har stor koncentrationsevne i søgeopgaverne, bider og gør rigtig godt. Han er absolut sund i hovedet på alle måder.',
    training_results: 'Aktiv politihund GR. 1. Mønstret i gr. 1. Avlskåret. Index 119. DM: N/N.',
    achievements: 'DM vinder af vinderklassen 2018, Dansk Politihundeforening. Nederholms Quik har parret Team Englunds Fanni.',
    extra_info: 'Super sundhedsstatistik på 10 kuld i DK: 13 hunde røntgenfotograferet – 12 stk. med HD:A + AD:0, 1 stk. med HD:B + AD:0.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/2906116/Nederholms%20Quik',
    photo_url: '/quik.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0022-4000-8000-000000000022',
    name: 'Hasco z Lomeckeho Polesi',
    gender: 'male',
    birthdate: null,
    sire_name: 'Kato Aritar Bastet',
    dam_name: 'Rebecca z Lipin',
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Hasco er en hund der har rigtig mange kvaliteter: Han arbejder rigtig godt i alle discipliner – har en stor koncentration på spor – arbejder super godt og hurtigt i lydighed. Han har særdeles gode greb og gør rigtig fint. Socialt er han meget omgængelig.',
    training_results: 'IPO 1. 3. plads IPO 1 DM 2017 (A:98 B:93 C:91). Index 114.',
    achievements: 'Hasco har d. 02.01.2019 parret Team Englunds Fanni. Far til 4 kuld i DK – alle fotograferede hunde med A og 0.',
    extra_info: 'DK 16608/2015',
    working_dog_url: 'https://da.working-dog.com/dogs-details/2611415/Hasco-z-Lomeckeho-Polesi',
    photo_url: '/hasco.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0023-4000-8000-000000000023',
    name: "Team Englund's Jack",
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: 'Ikke påvist',
    mental_description: 'Makker har sikkert væsen og god afstemning mellem drift og temperament. Til daglig fungerer han perfekt som politihund og familiehund, når han har fri. Han har fin størrelse og gode farver. Med sit bundsolide væsen, vil han være attraktiv til rigtig mange tæver.',
    training_results: 'Tjenestehund – Dansk Politi. P.t. i GR 3. Index 115.',
    achievements: 'Ud af søskeneflok på 9. Han og 2 andre hanner solgt til Politi med flotte og ensartede mentaltest. Kuldgentagelse i kuld "M" – DK Politi købte igen 3 hanner. Har d. 5. juni 2018 parret Team Englunds Gabby.',
    extra_info: 'DK13675/2017\nKaldenavn: Makker',
    working_dog_url: 'https://www.working-dog.com/dogs-details/6416746/Team-Englunds-Jack',
    photo_url: '/jack.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0024-4000-8000-000000000024',
    name: 'Irck de la Hutte du Berger',
    gender: 'male',
    birthdate: null,
    sire_name: 'Trick von Haus Penz',
    dam_name: 'Briska de la Hutte du Berger',
    hd_score: 'HD-Normal',
    ad_score: 'ED-Normal',
    ocd_status: null,
    mental_description: 'Irck er en virkelig fin hund med et sundt væsen, fin drift, kort kompakt og er ikke særlig stor/høj. Udenfor træningsbanen er han bare HELT i orden. En yderst tiltalende hund.',
    training_results: 'Tysk mester IPO 3 2017. WUSV VM deltager 2017. Arbejder rigtig fint i A, B og C.',
    achievements: 'Irck de la Hutte du Berger er d. 31.05.18 parret med Bayogi Yenka.',
    extra_info: 'SZ 2301806',
    working_dog_url: 'https://www.working-dog.com/dogs-details/1042669/Irck%20de%20la%20Hutte%20du%20Berger',
    photo_url: '/irck.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0025-4000-8000-000000000025',
    name: 'Bayogi Eika',
    gender: 'male',
    birthdate: null,
    sire_name: "Hulgård's Yupp",
    dam_name: 'Bayogi Villa',
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Eika er en hund, der har meget sikkert væsen, og masser af "ren" drift. Han er ret selvstændig og er en meget sporstærk hund. Han er helt "ren" i hovedet og socialt velafbalanceret. Han gennemførte politiets mentaltest med stort overskud og handlekraft og uden konfliktadfærd.',
    training_results: 'Tjenestehund – Dansk Politi Gr. II.',
    achievements: 'Eika og Yenka er forældre til "J" kuldet (født 10.08.16). 3 hanner fra kuldet har bestået Politiets mentaltest.',
    extra_info: 'DK05320/2013',
    working_dog_url: 'https://da.working-dog.com/dogs-details/5017058/Bayogi-Eika',
    photo_url: '/eika.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0026-4000-8000-000000000026',
    name: 'Toftegården Nero',
    gender: 'male',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: null,
    ad_score: 'AD 2',
    ocd_status: null,
    mental_description: 'I den forudgående mentaltest, der blev afholdt da hunden var 6,5 måned gammel, viste Nero stort overskud i alle momenter med bl.a. følgende kommentar: En venlig, omgængelig og meget driftig hund med høje tærskelværdier. En hund med et nervesystem, som er helt i balance.',
    training_results: 'Mønstret i GR I de sidste 5 år. Nedgravningshund. Fantastisk søgekoncentration. I sine unge dage med yderst effektivt GR C – forsvarsarbejde.',
    achievements: 'Deltaget i Nordisk Mesterskab for politi patruljehunde 2012 – lavede bedste bid i fulddragt.',
    extra_info: 'På sundhedssiden skyldes "2" i albuer 9 års arbejde som patruljehund – hunden (HD og AD fotograferet i januar 2017) er helt symptomfri på albuesiden.\n\nNero er helbror til Toftegården Nessi, der er stammor i Kennel Team Englund. Hun har leveret 6 fremragende kuld med rigtig mange tjenestehunde, 2x DM vindere osv.',
    working_dog_url: 'https://da.working-dog.com/dogs-details/5664389/Tofteg%C3%A5rden-Nero',
    photo_url: '/nero.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0027-4000-8000-000000000027',
    name: 'Sund Hund Yang',
    gender: 'male',
    birthdate: null,
    sire_name: "ChaDe's Atos",
    dam_name: 'Sund Hund Pampa',
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: 'Yang er en dejlig og velafbalanceret hund, der har et stort træningspotentiale.',
    training_results: 'PH: Vinderklassen, IPO 1, Avlskåret. Index 114.',
    achievements: 'Flere gange DM deltager i Dansk Politihundeforeningens program. Færdselsprøve og avlskåring.',
    extra_info: 'DK08766/2010',
    working_dog_url: 'https://da.working-dog.com/dogs-details/2601916/Sund-Hund-Yang',
    photo_url: '/yang.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1b2c3d4-0007-4000-8000-000000000007',
    name: 'Qutie von der Frisenklippe',
    gender: 'female',
    birthdate: null,
    sire_name: null,
    dam_name: null,
    hd_score: 'HD-A',
    ad_score: 'AD 0',
    ocd_status: null,
    mental_description: null,
    training_results: 'Tysk index 75',
    achievements: 'Har d. 1. februar født 4 hanner og 3 tæver.',
    extra_info: 'Qutie von der Frisenklippe bliver start december 2025 parret med Spike vom Adlerschrei. Begge har store kvaliteter. Hvalpene vil egnet sig perfekt til sport og tjenestehunde. Begge hunde har sundhed langt over middel, og begge er avlskåret. Vi planlægger nyt kuld i løbet af 2025. Reservationer er påbegyndt.\n\nFar til hvalpene er Alonso vom Verbotenen Wald.\n\nQutie er ud af en virkelig god brugshundelinie.\n\nVi har ledt en del efter endnu en tæve til vores avlsarbejde.\n\nDa vi fik muligheden for at købe Qutie måtte vi selvfølgelig gøre det.',
    working_dog_url: 'https://www.working-dog.com/dogs-details/7210096/Qutie-von-der-Friesenklippe',
    photo_url: '/qutie.jpg',
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockLitters: Litter[] = [
  {
    id: 'b1b2c3d4-0001-4000-8000-000000000001',
    title: "Englund's H-kuld",
    sire_name: 'Aldo Mersak',
    dam_name: 'Bellona vom Haus Mojü',
    sire_photo_url: '/kuld-han.jpg',
    dam_photo_url: '/kuld-taeve.jpg',
    birth_date: '2025-04-20',
    males_count: 4,
    females_count: 3,
    available: true,
    description: null,
    sort_order: 1,
    sire_hd: 'HD-A', sire_ad: 'AD 0', sire_ocd: 'Fri', sire_training: 'LTV1: Fri.',
    dam_hd: 'HD-A', dam_ad: 'AD 0', dam_ocd: 'Fri', dam_training: 'BH, StPr 1',
    sire_working_dog_url: null,
    dam_working_dog_url: 'https://www.working-dog.com/dogs-details/6434038/Bellona-vom-Haus-MoJ%C3%BC',
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'b1b2c3d4-0002-4000-8000-000000000002',
    title: 'Planlagt kuld',
    sire_name: 'Atos vom Haus Englund',
    dam_name: 'Gina vom Haus Englund',
    sire_photo_url: null,
    dam_photo_url: null,
    birth_date: null,
    males_count: 0,
    females_count: 0,
    available: false,
    description: 'Vi planlægger et nyt kuld til efteråret 2025. Gina vil blive parret med Atos for en spændende kombination af arbejdsevne og fantastisk mentalitet. Kontakt os for at komme på ventelisten.',
    sort_order: 2,
    sire_working_dog_url: null,
    dam_working_dog_url: null,
    created_at: '2025-05-01T00:00:00Z',
  },
]

export const mockNews: News[] = [
  {
    id: 'c1b2c3d4-0001-4000-8000-000000000001',
    title: 'Rex opnår VA på Bundessieger!',
    content: 'Vi er utroligt stolte over at vores Rex vom Haus Englund har opnået den fornemme VA-placering (Vorzüglich Auslese) på årets Bundessieger i Nürnberg. Det er en enorm anerkendelse af hans kvalitet som avlshan og en milepæl for vores kennel. Rex viste sig fra sin bedste side med fantastisk bevægelse og temperament. Tak til alle der hepper på os!',
    photo_path: null,
    published_at: '2025-05-15T00:00:00Z',
    created_at: '2025-05-15T00:00:00Z',
  },
  {
    id: 'c1b2c3d4-0002-4000-8000-000000000002',
    title: 'Nye hvalpe er født!',
    content: 'Den 20. april blev vi velsignet med et smukt kuld på 7 hvalpe fra Rex og Donja. 4 hanner og 3 tæver, alle sunde og stærke. Moderen har det fantastisk og hvalpene vokser som ukrudt. Vi begynder med besøgstider fra uge 5. Kontakt os hvis du er interesseret.',
    photo_path: null,
    published_at: '2025-04-20T00:00:00Z',
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'c1b2c3d4-0003-4000-8000-000000000003',
    title: 'Gina bestod IPO1 med bravur',
    content: 'Vores unge Gina vom Haus Englund bestod i dag sin IPO1-prøve med imponerende 280 point. Hun viste sig særligt stærk i spordisciplinen med 96 point. Vi er meget tilfredse med hendes udvikling og ser frem til næste trin i hendes uddannelse.',
    photo_path: null,
    published_at: '2025-03-10T00:00:00Z',
    created_at: '2025-03-10T00:00:00Z',
  },
]
